project_name: akoctl
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: akoctl

archives:
  - formats: [ 'tar.gz' ]
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      akoctl_{{ .Tag }}_{{ .Os }}_{{ .Arch -}}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  disable: true
release:
  prerelease: 'true'
version: 2